Repository redBorder/cookbook-kafka, pull requests merged in 2024-05, with the labels that each got.

#15 Topics are not auto-creating in the proxy
  resources/providers/config.rb
Labels: size/XS, kind/bug

#14 kafka topic leader is gone when new kafka broker id is assigned
  resources/providers/config.rb
  resources/templates/default/kafka_server.properties.erb
Labels: size/XS, kind/bug

#16 Proxy is creating kafka topics of the manager
  resources/providers/config.rb
Labels: size/M, kind/bug

#17 Release 1.0.9
  CHANGELOG.md
  resources/metadata.rb
  resources/providers/config.rb
  resources/templates/default/kafka_server.properties.erb
Labels: size/S, kind/documentation, kind/bug, size/L

#19 Release 1.0.10
  CHANGELOG.md
  resources/attributes/default.rb
  resources/metadata.rb
  resources/providers/config.rb
  resources/recipes/default.rb
  resources/resources/config.rb
Labels: kind/documentation, size/L, refactor
